Repository Scapture-official/Scapture-Server, pull requests merged in 2024-07, with the labels that each got.

#5 ⚙️ [Setting] Entity 생성 - User, Video, Stadium
  scapture/src/main/java/com/server/scapture/domain/Role.java
  scapture/src/main/java/com/server/scapture/domain/Stadium.java
  scapture/src/main/java/com/server/scapture/domain/User.java
  scapture/src/main/java/com/server/scapture/domain/Video.java
  scapture/src/main/java/com/server/scapture/video/controller/VideoController.java
  scapture/src/main/java/com/server/scapture/video/dto/VideoCreateRequestDto.java
  scapture/src/main/java/com/server/scapture/video/dto/VideoGetResponseDto.java
  scapture/src/main/java/com/server/scapture/video/service/VideoService.java
  scapture/src/main/java/com/server/scapture/video/service/VideoServiceImpl.java
  scapture/src/main/resources/application.properties
Labels: ⚙️ Setting, 🎳 현승

#9 Entity 생성 - Field, Schedule, Comment
  scapture/src/main/java/com/server/scapture/domain/Comment.java
  scapture/src/main/java/com/server/scapture/domain/Field.java
  scapture/src/main/java/com/server/scapture/domain/Schedule.java
  scapture/src/main/java/com/server/scapture/video/controller/VideoController.java
Labels: ⚙️ Setting, 🎳 현승

#10 ⚙️ [Setting] Entity 생성 - Image, Subscribe. Event
  scapture/src/main/java/com/server/scapture/domain/Event.java
  scapture/src/main/java/com/server/scapture/domain/Image.java
  scapture/src/main/java/com/server/scapture/domain/Subscribe.java
  scapture/src/main/java/com/server/scapture/domain/User.java
  scapture/src/main/java/com/server/scapture/domain/Video.java
Labels: ⚙️ Setting, 🎳 현승

#11 ⚙️ [Setting] Entity 생성 - Reservation, VideoLike, CommentLike, Store, Download
  scapture/src/main/java/com/server/scapture/domain/CommentLike.java
  scapture/src/main/java/com/server/scapture/domain/Download.java
  scapture/src/main/java/com/server/scapture/domain/Reservation.java
  scapture/src/main/java/com/server/scapture/domain/Store.java
  scapture/src/main/java/com/server/scapture/domain/VideoLike.java
Labels: ⚙️ Setting, 🎳 현승

#22 [FEAT] 소셜로그인 API 구현 - 기본 세팅
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  scapture/src/main/java/com/server/scapture/user/controller/AuthController.java
  scapture/src/main/java/com/server/scapture/user/dto/AuthResponseDto.java
  scapture/src/main/java/com/server/scapture/user/repository/OAuthRepository.java
  scapture/src/main/java/com/server/scapture/user/service/CustomOAuth2UserService.java
  settings.gradle
  src/main/java/com/server/scapture/ScaptureApplication.java
  src/main/java/com/server/scapture/domain/Comment.java
  src/main/java/com/server/scapture/domain/CommentLike.java
  src/main/java/com/server/scapture/domain/Download.java
  src/main/java/com/server/scapture/domain/Event.java
  src/main/java/com/server/scapture/domain/Field.java
  src/main/java/com/server/scapture/domain/Image.java
  src/main/java/com/server/scapture/domain/Reservation.java
  src/main/java/com/server/scapture/domain/Role.java
  src/main/java/com/server/scapture/domain/Schedule.java
  src/main/java/com/server/scapture/domain/Stadium.java
  src/main/java/com/server/scapture/domain/Store.java
  src/main/java/com/server/scapture/domain/Subscribe.java
  src/main/java/com/server/scapture/domain/User.java
  src/main/java/com/server/scapture/domain/Video.java
  src/main/java/com/server/scapture/domain/VideoLike.java
  src/main/java/com/server/scapture/util/S3/S3Service.java
  src/main/java/com/server/scapture/util/config/AwsConfig.java
  src/main/java/com/server/scapture/util/config/CorsConfig.java
  src/main/java/com/server/scapture/util/config/SecurityConfig.java
  src/main/java/com/server/scapture/util/controller/CustomErrorController.java
  src/main/java/com/server/scapture/util/entity/BaseEntity.java
  src/main/java/com/server/scapture/util/exception/GlobalExceptionHandler.java
  src/main/java/com/server/scapture/util/response/CustomAPIResponse.java
  src/main/java/com/server/scapture/video/controller/VideoController.java
  src/main/java/com/server/scapture/video/dto/VideoCreateRequestDto.java
  src/main/java/com/server/scapture/video/repository/VideoRepository.java
  src/main/java/com/server/scapture/video/service/VideoService.java
  src/main/java/com/server/scapture/video/service/VideoServiceImpl.java
  src/main/resources/application.properties
  src/test/java/com/server/scapture/ScaptureApplicationTests.java
Labels: ✨ Feat, 🍀 혜진

#23 ⬆️ 소셜로그인 API 구현 - 의존성 추가
  scapture/build.gradle
Labels: ⚙️ Setting, 🍀 혜진

#26 [User] 소셜로그인 API 구현
  scapture/build.gradle
  scapture/src/main/java/com/server/scapture/domain/User.java
  scapture/src/main/java/com/server/scapture/user/JwtUtil.java
  scapture/src/main/java/com/server/scapture/user/dto/AuthResponseDto.java
  scapture/src/main/java/com/server/scapture/user/dto/GoogleUserInfo.java
  scapture/src/main/java/com/server/scapture/user/dto/KakaoUserInfo.java
  scapture/src/main/java/com/server/scapture/user/dto/NaverUserInfo.java
  scapture/src/main/java/com/server/scapture/user/dto/OAuth2UserInfo.java
  scapture/src/main/java/com/server/scapture/user/handler/OAuthLoginFailureHandler.java
  scapture/src/main/java/com/server/scapture/user/handler/OAuthLoginSuccessHandler.java
  scapture/src/main/java/com/server/scapture/user/repository/OAuthRepository.java
  scapture/src/main/java/com/server/scapture/user/repository/UserRepository.java
  scapture/src/main/java/com/server/scapture/user/service/CustomOAuth2UserService.java
  scapture/src/main/java/com/server/scapture/util/config/SecurityConfig.java
  scapture/src/main/resources/application.properties
Labels: ✨ Feat, 🍀 혜진

#28 [User] 소셜로그인 API 구현 - 수정
  scapture/build.gradle
  scapture/src/main/java/com/server/scapture/user/JwtUtil.java
  scapture/src/main/java/com/server/scapture/user/handler/OAuthLoginSuccessHandler.java
  scapture/src/main/java/com/server/scapture/user/repository/UserRepository.java
Labels: 🚨 Fix, 🍀 혜진

#31 🛠️ [Refactor] socialId -> providerId
  scapture/src/main/java/com/server/scapture/domain/User.java
Labels: 🛠️ Refactoring, 🎳 현승

#32 ✨[Feat] 경기장 생성 API 구현
  scapture/src/main/java/com/server/scapture/image/repository/ImageRepository.java
  scapture/src/main/java/com/server/scapture/stadium/controller/StadiumController.java
  scapture/src/main/java/com/server/scapture/stadium/dto/CreateStadiumRequestDto.java
  scapture/src/main/java/com/server/scapture/stadium/dto/CreateStadiumResponseDto.java
  scapture/src/main/java/com/server/scapture/stadium/repository/StadiumRepository.java
  scapture/src/main/java/com/server/scapture/stadium/service/StadiumService.java
  scapture/src/main/java/com/server/scapture/stadium/service/StadiumServiceImpl.java
  scapture/src/main/java/com/server/scapture/util/S3/S3Service.java
  scapture/src/main/java/com/server/scapture/video/service/VideoServiceImpl.java
  scapture/src/main/resources/application.properties
Labels: ✨ Feat, 🎳 현승

#33 ✨ [Feat] 경기장 전체 조회 API 구현
  scapture/src/main/java/com/server/scapture/image/repository/ImageRepository.java
  scapture/src/main/java/com/server/scapture/stadium/controller/StadiumController.java
  scapture/src/main/java/com/server/scapture/stadium/dto/GetStadiumByCityAndStateResponseDto.java
  scapture/src/main/java/com/server/scapture/stadium/repository/StadiumRepository.java
  scapture/src/main/java/com/server/scapture/stadium/service/StadiumService.java
  scapture/src/main/java/com/server/scapture/stadium/service/StadiumServiceImpl.java
  scapture/src/main/java/com/server/scapture/user/JwtUtil.java
  scapture/src/main/java/com/server/scapture/user/handler/OAuthLoginSuccessHandler.java
  scapture/src/main/java/com/server/scapture/util/config/SecurityConfig.java
Labels: ✨ Feat, 🎳 현승

#41 ✨[Feat] 경기장 검색 API 구현
  scapture/src/main/java/com/server/scapture/stadium/controller/StadiumController.java
  scapture/src/main/java/com/server/scapture/stadium/dto/GetStadiumResponseDto.java
  scapture/src/main/java/com/server/scapture/stadium/repository/StadiumRepository.java
  scapture/src/main/java/com/server/scapture/stadium/service/StadiumService.java
  scapture/src/main/java/com/server/scapture/stadium/service/StadiumServiceImpl.java
Labels: ✨ Feat, 🎳 현승

#42 🚨 [Fix] 구장 경기장 조회 API 수정
  scapture/src/main/java/com/server/scapture/stadium/service/StadiumServiceImpl.java
Labels: 🚨 Fix, 🎳 현승

#47 ✨ [Feat] 운영 시간 생성 API 구현
  scapture/src/main/java/com/server/scapture/domain/Schedule.java
  scapture/src/main/java/com/server/scapture/schedule/controller/ScheduleController.java
  scapture/src/main/java/com/server/scapture/schedule/dto/CreateScheduleRequestDto.java
  scapture/src/main/java/com/server/scapture/schedule/repository/ScheduleRepository.java
  scapture/src/main/java/com/server/scapture/schedule/service/ScheduleService.java
  scapture/src/main/java/com/server/scapture/schedule/service/ScheduleServiceImpl.java
Labels: ✨ Feat, 🎳 현승

#51 [FEAT] 카카오 소셜로그인 API 구현- 인가코드 받기, 접근 토큰 받기, 사용자 정보 받기
  scapture/build.gradle
  scapture/src/main/java/com/server/scapture/oauth/controller/SignController.java
  scapture/src/main/java/com/server/scapture/oauth/dto/KakaoApi.java
  scapture/src/main/java/com/server/scapture/oauth/service/SignService.java
  scapture/src/main/java/com/server/scapture/oauth/service/SignServiceImpl.java
  scapture/src/main/resources/application.properties
  scapture/src/main/resources/logback-spring.xml
Labels: ✨ Feat, 🍀 혜진

#55 [Feat] 카카오 소셜로그인 API 관련 세팅- UserInfo Dto 생성, 회원 저장 관련 세팅
  scapture/src/main/java/com/server/scapture/oauth/controller/SignController.java
  scapture/src/main/java/com/server/scapture/oauth/dto/UserInfo.java
  scapture/src/main/java/com/server/scapture/oauth/service/SignService.java
  scapture/src/main/java/com/server/scapture/oauth/service/SignServiceImpl.java
Labels: 🚨 Fix, ✨ Feat, 🍀 혜진

#57 ✨ [Feat] 카카오 소셜로그인 API 구현 - 로그인/회원가입
  scapture/src/main/java/com/server/scapture/oauth/controller/SignController.java
  scapture/src/main/java/com/server/scapture/oauth/dto/UserInfo.java
  scapture/src/main/java/com/server/scapture/oauth/service/SignService.java
  scapture/src/main/java/com/server/scapture/oauth/service/SignServiceImpl.java
  scapture/src/main/java/com/server/scapture/user/repository/UserRepository.java
  scapture/src/main/java/com/server/scapture/util/entity/OAuthException.java
Labels: ✨ Feat, 🍀 혜진

#59 ✨ [Feat] 카카오 소셜로그인 API 구현 완료!! - JWT 토큰 발행 후 리턴
  scapture/src/main/java/com/server/scapture/oauth/dto/KakaoApi.java
  scapture/src/main/java/com/server/scapture/oauth/service/SignService.java
  scapture/src/main/java/com/server/scapture/oauth/service/SignServiceImpl.java
  scapture/src/main/java/com/server/scapture/user/JwtUtil.java
  scapture/src/main/java/com/server/scapture/user/controller/AuthController.java
  scapture/src/main/java/com/server/scapture/user/dto/GoogleUserInfo.java
  scapture/src/main/java/com/server/scapture/user/dto/KakaoUserInfo.java
  scapture/src/main/java/com/server/scapture/user/dto/NaverUserInfo.java
  scapture/src/main/java/com/server/scapture/user/dto/OAuth2UserInfo.java
  scapture/src/main/java/com/server/scapture/user/handler/OAuthLoginFailureHandler.java
  scapture/src/main/java/com/server/scapture/user/handler/OAuthLoginSuccessHandler.java
  scapture/src/main/java/com/server/scapture/user/service/CustomOAuth2UserService.java
  scapture/src/main/java/com/server/scapture/user/service/UserService.java
  scapture/src/main/java/com/server/scapture/user/service/UserServiceImpl.java
  scapture/src/main/java/com/server/scapture/util/config/SecurityConfig.java
  scapture/src/main/java/com/server/scapture/util/jwt/JwtUtil.java
  scapture/src/main/resources/application.properties
Labels: ✨ Feat, 🍀 혜진

#61 📝 [Docs] 카카오 소셜로그인 - 공부 및 정리
  scapture/src/main/java/com/server/scapture/util/config/SecurityConfig.java
Labels: 📄 Docs, 🍀 혜진

#65 🚨 [Fix] 운영 일정 생성 API 수정 - 예약 여부 Default 값 주입
  scapture/src/main/java/com/server/scapture/schedule/service/ScheduleServiceImpl.java
Labels: 🚨 Fix, 🎳 현승

#68 🚚 [Refactoring]소셜로그인 패키지 구조 조정
  scapture/.gitignore
  scapture/src/main/java/com/server/scapture/oauth/jwt/JwtUtil.java
  scapture/src/main/java/com/server/scapture/oauth/service/SignServiceImpl.java
  scapture/src/main/java/com/server/scapture/user/dto/GoogleUserInfo.java
  scapture/src/main/java/com/server/scapture/user/dto/KakaoUserInfo.java
  scapture/src/main/java/com/server/scapture/user/dto/NaverUserInfo.java
  scapture/src/main/java/com/server/scapture/user/dto/OAuth2UserInfo.java
  scapture/src/main/java/com/server/scapture/user/service/UserServiceImpl.java
Labels: ✨ Feat, 🍀 혜진

#69 ✨[Feat] 구장 운영시간 조회 API 구현
  scapture/src/main/java/com/server/scapture/schedule/repository/ScheduleRepository.java
  scapture/src/main/java/com/server/scapture/stadium/controller/StadiumController.java
  scapture/src/main/java/com/server/scapture/stadium/dto/GetScheduleByFieldAndDateResponseDto.java
  scapture/src/main/java/com/server/scapture/stadium/service/StadiumService.java
  scapture/src/main/java/com/server/scapture/stadium/service/StadiumServiceImpl.java
  scapture/src/main/java/com/server/scapture/video/repository/VideoRepository.java
  scapture/src/main/resources/application.properties
  scapture/src/main/resources/logback-spring.xml
Labels: ✨ Feat, 🎳 현승

#70 🚨 [Fix] 카카오 소셜로그인 API 구현 - application-secret.properties 설정
  scapture/src/main/java/com/server/scapture/oauth/jwt/JwtUtil.java
  scapture/src/main/java/com/server/scapture/oauth/service/SignServiceImpl.java
Labels: 🚨 Fix, 🎳 현승

#79 ✨ [Feat] 경기 영상 조회 API 구현
  scapture/src/main/java/com/server/scapture/field/controller/FieldController.java
  scapture/src/main/java/com/server/scapture/schedule/controller/ScheduleController.java
  scapture/src/main/java/com/server/scapture/stadium/controller/StadiumController.java
  scapture/src/main/java/com/server/scapture/video/controller/VideoController.java
  scapture/src/main/java/com/server/scapture/video/dto/GetVideosResponseDto.java
  scapture/src/main/java/com/server/scapture/video/repository/VideoRepository.java
  scapture/src/main/java/com/server/scapture/video/service/VideoService.java
  scapture/src/main/java/com/server/scapture/video/service/VideoServiceImpl.java
Labels: ✨ Feat, 🎳 현승

#80 ✨ [Feat] 인기 영상 조회 API 구현
  scapture/src/main/java/com/server/scapture/video/controller/VideoController.java
  scapture/src/main/java/com/server/scapture/video/dto/GetVideosByLikeCountResponseDto.java
  scapture/src/main/java/com/server/scapture/video/repository/VideoRepository.java
  scapture/src/main/java/com/server/scapture/video/service/VideoService.java
  scapture/src/main/java/com/server/scapture/video/service/VideoServiceImpl.java
Labels: ✨ Feat, 🎳 현승

#82 ✨ [Feat] 소셜로그인 - JWT 토큰을 통한 해당 User 정보 조회 기능 구현
  scapture/src/main/java/com/server/scapture/oauth/controller/SignController.java
  scapture/src/main/java/com/server/scapture/oauth/jwt/JwtUtil.java
Labels: ✨ Feat, 🍀 혜진

#83 ✨ [Feat] 영상 좋아요 추가 / 해제 API 구현
  scapture/src/main/java/com/server/scapture/domain/Video.java
  scapture/src/main/java/com/server/scapture/video/controller/VideoController.java
  scapture/src/main/java/com/server/scapture/video/service/VideoService.java
  scapture/src/main/java/com/server/scapture/video/service/VideoServiceImpl.java
  scapture/src/main/java/com/server/scapture/videoLike/repository/VideoLikeRepository.java
Labels: ✨ Feat, 🎳 현승

#84 ✨ [Feat] 영상 저장 / 해제 API 구현
  scapture/src/main/java/com/server/scapture/store/repository/StoreRepository.java
  scapture/src/main/java/com/server/scapture/video/controller/VideoController.java
  scapture/src/main/java/com/server/scapture/video/service/VideoService.java
  scapture/src/main/java/com/server/scapture/video/service/VideoServiceImpl.java
Labels: 🎳 현승, ✨ Feat

#85 ✨ [Feat] 저장 영상 조회 API 구현
  scapture/src/main/java/com/server/scapture/store/repository/StoreRepository.java
  scapture/src/main/java/com/server/scapture/video/controller/VideoController.java
  scapture/src/main/java/com/server/scapture/video/dto/GetStoredVideoResponseDto.java
  scapture/src/main/java/com/server/scapture/video/service/VideoService.java
  scapture/src/main/java/com/server/scapture/video/service/VideoServiceImpl.java
Labels: 🎳 현승, ✨ Feat

#87 ✨ [Feat] 네이버 소셜로그인 구현
  scapture/src/main/java/com/server/scapture/oauth/controller/SignController.java
  scapture/src/main/java/com/server/scapture/oauth/dto/KakaoApi.java
  scapture/src/main/java/com/server/scapture/oauth/jwt/JwtUtil.java
  scapture/src/main/java/com/server/scapture/oauth/service/AbstractSocialLoginService.java
  scapture/src/main/java/com/server/scapture/oauth/service/KakaoLoginService.java
  scapture/src/main/java/com/server/scapture/oauth/service/KakaoLoginServiceImpl.java
  scapture/src/main/java/com/server/scapture/oauth/service/NaverLoginService.java
  scapture/src/main/java/com/server/scapture/oauth/service/NaverLoginServiceImpl.java
  scapture/src/main/java/com/server/scapture/oauth/service/SocialLoginService.java
  scapture/src/main/resources/application.properties
Labels: 🍀 혜진, ✨ Feat

#89 ✨ [Feat] 구글 소셜로그인 API 구현
  scapture/src/main/java/com/server/scapture/oauth/controller/SignController.java
  scapture/src/main/java/com/server/scapture/oauth/jwt/JwtUtil.java
  scapture/src/main/java/com/server/scapture/oauth/service/GoogleLoginService.java
  scapture/src/main/java/com/server/scapture/oauth/service/GoogleLoginServiceImpl.java
Labels: 🍀 혜진, ✨ Feat

#94 ✨ [Feat] 영상 다운로드 권한 부여 API 구현
  scapture/src/main/java/com/server/scapture/download/repository/DownloadRepository.java
  scapture/src/main/java/com/server/scapture/video/controller/VideoController.java
  scapture/src/main/java/com/server/scapture/video/service/VideoService.java
  scapture/src/main/java/com/server/scapture/video/service/VideoServiceImpl.java
Labels: 🎳 현승, ✨ Feat

#95 ✨ [Feat] 영상 다운로드 권한 조회 API 구현
  scapture/src/main/java/com/server/scapture/video/controller/VideoController.java
  scapture/src/main/java/com/server/scapture/video/service/VideoService.java
  scapture/src/main/java/com/server/scapture/video/service/VideoServiceImpl.java
Labels: 🎳 현승, ✨ Feat

#100 ✨ [Feat] 구장 예약 API 구현
  scapture/src/main/java/com/server/scapture/reservation/controller/ReservationController.java
  scapture/src/main/java/com/server/scapture/reservation/repository/ReservationRepository.java
  scapture/src/main/java/com/server/scapture/reservation/service/ReservationService.java
  scapture/src/main/java/com/server/scapture/reservation/service/ReservationServideImpl.java
Labels: 🎳 현승, ✨ Feat

#105 ✨ [Feat] 버내너 잔액 조회 API 구현
  scapture/src/main/java/com/server/scapture/domain/Subscribe.java
  scapture/src/main/java/com/server/scapture/oauth/jwt/JwtUtil.java
  scapture/src/main/java/com/server/scapture/subscribe/repository/SubscribeRepository.java
  scapture/src/main/java/com/server/scapture/user/controller/UserController.java
  scapture/src/main/java/com/server/scapture/user/dto/BananaBalanceResponseDto.java
  scapture/src/main/java/com/server/scapture/user/repository/UserRepository.java
  scapture/src/main/java/com/server/scapture/user/service/UserService.java
  scapture/src/main/java/com/server/scapture/user/service/UserServiceImpl.java
Labels: 🍀 혜진, ✨ Feat

#107 ✨ [Feat] 구장 예약 일정 조회 API 구현
  scapture/src/main/java/com/server/scapture/reservation/controller/ReservationController.java
  scapture/src/main/java/com/server/scapture/reservation/dto/GetReservationResponseDto.java
  scapture/src/main/java/com/server/scapture/reservation/dto/SortReservationDto.java
  scapture/src/main/java/com/server/scapture/reservation/service/ReservationService.java
  scapture/src/main/java/com/server/scapture/reservation/service/ReservationServiceImpl.java
  scapture/src/main/java/com/server/scapture/reservation/service/ReservationServideImpl.java
Labels: 🎳 현승, ✨ Feat

#108 ✨ [Feat] 댓글 작성 API 구현
  scapture/src/main/java/com/server/scapture/comment/controller/CommentController.java
  scapture/src/main/java/com/server/scapture/comment/dto/CreateCommentRequestDto.java
  scapture/src/main/java/com/server/scapture/comment/repository/CommentRepository.java
  scapture/src/main/java/com/server/scapture/comment/service/CommentService.java
  scapture/src/main/java/com/server/scapture/comment/service/CommentServiceImpl.java
Labels: 🎳 현승, ✨ Feat

#111 ✨ [Feat] 댓글 좋아요 추가 API 구현
  scapture/src/main/java/com/server/scapture/comment/controller/CommentController.java
  scapture/src/main/java/com/server/scapture/comment/service/CommentService.java
  scapture/src/main/java/com/server/scapture/comment/service/CommentServiceImpl.java
  scapture/src/main/java/com/server/scapture/commentLike/repository/CommentLikeRepository.java
  scapture/src/main/java/com/server/scapture/reservation/service/ReservationServiceImpl.java
Labels: 🎳 현승, ✨ Feat

#112 ✨ [Feat] 댓글 좋아요 해제 API 구현
  scapture/src/main/java/com/server/scapture/comment/controller/CommentController.java
  scapture/src/main/java/com/server/scapture/comment/service/CommentService.java
  scapture/src/main/java/com/server/scapture/comment/service/CommentServiceImpl.java
  scapture/src/main/java/com/server/scapture/domain/Comment.java
Labels: 🎳 현승, ✨ Feat

#114 ✨ [Feat] 버내너 충전 API 구현
  scapture/src/main/java/com/server/scapture/domain/User.java
  scapture/src/main/java/com/server/scapture/oauth/jwt/JwtUtil.java
  scapture/src/main/java/com/server/scapture/user/controller/UserController.java
  scapture/src/main/java/com/server/scapture/user/dto/BananaAddResponseDto.java
  scapture/src/main/java/com/server/scapture/user/service/UserService.java
  scapture/src/main/java/com/server/scapture/user/service/UserServiceImpl.java
Labels: 🍀 혜진, ✨ Feat

#121 🚨 [Fix] 소셜로그인 - jwt.secret 값 넣을때 발생하는 문제 해결
  scapture/src/main/java/com/server/scapture/oauth/jwt/JwtUtil.java
Labels: 🚨 Fix, 🍀 혜진

#122 ✨ [Feat] 프로필 조회 API 구현
  scapture/src/main/java/com/server/scapture/user/controller/UserController.java
  scapture/src/main/java/com/server/scapture/user/dto/UserProfileDto.java
  scapture/src/main/java/com/server/scapture/user/service/UserService.java
  scapture/src/main/java/com/server/scapture/user/service/UserServiceImpl.java
Labels: 🍀 혜진, ✨ Feat

#125 ✨ [Feat] checkTier 메서드 생성
  scapture/src/main/java/com/server/scapture/subscribe/repository/SubscribeRepository.java
  scapture/src/main/java/com/server/scapture/subscribe/service/SubscribeService.java
  scapture/src/main/java/com/server/scapture/subscribe/service/SubscribeServiceImpl.java
Labels: 🍀 혜진, ✨ Feat

#127 ✨ [Feat] 프로필 조회 API - checkRole() 추가
  scapture/src/main/java/com/server/scapture/user/service/UserServiceImpl.java
Labels: 🍀 혜진, ✨ Feat

#128 ✨ [Feat] 구독 갱신/생성 API 구현
  scapture/src/main/java/com/server/scapture/user/controller/UserController.java
  scapture/src/main/java/com/server/scapture/user/dto/SubscribeResponseDto.java
  scapture/src/main/java/com/server/scapture/user/service/UserService.java
  scapture/src/main/java/com/server/scapture/user/service/UserServiceImpl.java
Labels: 🍀 혜진, ✨ Feat

#130 ✨ [Feat] 댓글 전체 조회 API 구현
  scapture/src/main/java/com/server/scapture/comment/controller/CommentController.java
  scapture/src/main/java/com/server/scapture/comment/dto/GetCommentResponseDto.java
  scapture/src/main/java/com/server/scapture/comment/repository/CommentRepository.java
  scapture/src/main/java/com/server/scapture/comment/service/CommentService.java
  scapture/src/main/java/com/server/scapture/comment/service/CommentServiceImpl.java
  scapture/src/main/java/com/server/scapture/user/repository/UserRepository.java
Labels: 🎳 현승, ✨ Feat

#132 ✨ [Feat] S3 User Profile image 수정 Method 추가
  scapture/src/main/java/com/server/scapture/stadium/service/StadiumServiceImpl.java
  scapture/src/main/java/com/server/scapture/util/S3/S3Service.java
  scapture/src/main/resources/application.properties
Labels: 🎳 현승, ✨ Feat

#133 ✨ [Feat] 예약 내역 조회 API 구현
  scapture/src/main/java/com/server/scapture/reservation/repository/ReservationRepository.java
  scapture/src/main/java/com/server/scapture/user/controller/UserController.java
  scapture/src/main/java/com/server/scapture/user/dto/ReservationResponseDto.java
  scapture/src/main/java/com/server/scapture/user/service/UserService.java
  scapture/src/main/java/com/server/scapture/user/service/UserServiceImpl.java
  scapture/src/main/java/com/server/scapture/util/date/DateUtil.java
Labels: 🍀 혜진, ✨ Feat

#135 ✨ [Feat] localDateTime formatting 관련 메서드 구현
  scapture/src/main/java/com/server/scapture/util/date/DateUtil.java
Labels: 🍀 혜진, ✨ Feat

#136 ✨ [Feat] 프로필 편집 API 구현
  scapture/src/main/java/com/server/scapture/domain/User.java
  scapture/src/main/java/com/server/scapture/user/controller/UserController.java
  scapture/src/main/java/com/server/scapture/user/dto/ProfileEditDto.java
  scapture/src/main/java/com/server/scapture/user/dto/ProfileViewDto.java
  scapture/src/main/java/com/server/scapture/user/dto/UserProfileDto.java
  scapture/src/main/java/com/server/scapture/user/service/UserService.java
  scapture/src/main/java/com/server/scapture/user/service/UserServiceImpl.java
  scapture/src/main/java/com/server/scapture/util/S3/S3Service.java
Labels: 🍀 혜진, ✨ Feat

#138 🚨 [FIx] 영상 세부 조회 API 수정
  scapture/src/main/java/com/server/scapture/domain/Video.java
  scapture/src/main/java/com/server/scapture/video/dto/GetStadiumInfoDto.java
  scapture/src/main/java/com/server/scapture/video/dto/GetVideoDetailResponseDto.java
  scapture/src/main/java/com/server/scapture/video/service/VideoServiceImpl.java
Labels: 🚨 Fix, 🎳 현승

#139 🚨 [Fix] 영상 생성 - 조회수 추가
  scapture/src/main/java/com/server/scapture/video/service/VideoServiceImpl.java
Labels: 🚨 Fix, 🎳 현승

#140 🚨 [Fix] 경기 영상 조회 API - 조회수 추가
  scapture/src/main/java/com/server/scapture/video/dto/GetVideosResponseDto.java
  scapture/src/main/java/com/server/scapture/video/service/VideoServiceImpl.java
Labels: 🚨 Fix, 🎳 현승

#141 🚨 [Fix] 인기 영상 조회 API 수정
  scapture/src/main/java/com/server/scapture/video/dto/GetVideosByLikeCountResponseDto.java
  scapture/src/main/java/com/server/scapture/video/service/VideoServiceImpl.java
Labels: 🚨 Fix, 🎳 현승

#142 [Fix] 영상 다운로드 권한 부여 API 수정
  scapture/src/main/java/com/server/scapture/domain/User.java
  scapture/src/main/java/com/server/scapture/video/service/VideoServiceImpl.java
Labels: 🚨 Fix, 🎳 현승

#149 🚨 [Fix] Comment 조회 API
  scapture/src/main/java/com/server/scapture/comment/controller/CommentController.java
  scapture/src/main/java/com/server/scapture/comment/service/CommentServiceImpl.java
Labels: 🚨 Fix, 🎳 현승

#150 🚨 [Fix] 영상 세부 조회 API 수정
  scapture/src/main/java/com/server/scapture/video/controller/VideoController.java
  scapture/src/main/java/com/server/scapture/video/service/VideoServiceImpl.java
Labels: 🚨 Fix, 🎳 현승

#153 🚨 [Fix] 운영 일정 생성 API 수정
  scapture/src/main/java/com/server/scapture/schedule/controller/ScheduleController.java
  scapture/src/main/java/com/server/scapture/schedule/dto/CreateScheduleRequestDto.java
  scapture/src/main/java/com/server/scapture/schedule/service/ScheduleService.java
  scapture/src/main/java/com/server/scapture/schedule/service/ScheduleServiceImpl.java
Labels: 🚨 Fix, 🎳 현승

#156 🚨 [FIx] 댓글 전체 조회 API 수정
  scapture/src/main/java/com/server/scapture/comment/dto/GetCommentResponseDto.java
  scapture/src/main/java/com/server/scapture/comment/service/CommentServiceImpl.java
Labels: 🚨 Fix, 🎳 현승

#157 🚨 [Fix] 인기영상 조회 API 수정
  scapture/src/main/java/com/server/scapture/video/service/VideoServiceImpl.java
Labels: 🚨 Fix, 🎳 현승

#159 🚨 [Fix] 소셜로그인 - Role 들어가도록 수정
  scapture/src/main/java/com/server/scapture/oauth/dto/UserInfo.java
Labels: 🚨 Fix, 🍀 혜진

#160 ✨ [Release] 소셜로그인 로컬 -> 배포
  scapture/src/main/java/com/server/scapture/user/dto/SubscribeResponseDto.java
Labels: 🌐 Release, 🍀 혜진

#162 🚨 [Fix] 영상 세부 조회 API 수정 - Response 수정
  scapture/src/main/java/com/server/scapture/video/dto/GetVideoDetailResponseDto.java
  scapture/src/main/java/com/server/scapture/video/service/VideoServiceImpl.java
Labels: 🚨 Fix, 🎳 현승

#164 🚨 [Fix] 영상 세부 조회 API 수정 - 구장 사진 첨부
  scapture/src/main/java/com/server/scapture/video/dto/GetStadiumInfoDto.java
  scapture/src/main/java/com/server/scapture/video/service/VideoServiceImpl.java
Labels: 🚨 Fix, 🎳 현승

#168 🚨 [Fix] 소셜로그인 - 응답 형식 변환 data -> data.token
  scapture/src/main/java/com/server/scapture/oauth/dto/SocialLoginResponseDto.java
  scapture/src/main/java/com/server/scapture/oauth/service/AbstractSocialLoginService.java
Labels: 🚨 Fix, 🍀 혜진

#169 ✅ [Test] 프로필 조회 - 구독중인 경우 test
  scapture/src/main/java/com/server/scapture/user/controller/UserController.java
Labels: 🍀 혜진, :white_check_mark: Test

#172 🚨 [Fix] 경기장 세부 조회 API - Response 운영 시간 추가
  scapture/src/main/java/com/server/scapture/stadium/dto/GetStadiumDetailDto.java
  scapture/src/main/java/com/server/scapture/stadium/service/StadiumServiceImpl.java
Labels: 🚨 Fix, 🎳 현승
