Repository Scapture-official/Scapture-Server, pull requests merged in 2024-08, with the labels that each got.

#174 🚨 [FIx] 구장 예약 일정 조회 API 수정
  scapture/src/main/java/com/server/scapture/reservation/controller/ReservationController.java
  scapture/src/main/java/com/server/scapture/reservation/service/ReservationService.java
  scapture/src/main/java/com/server/scapture/reservation/service/ReservationServiceImpl.java
Labels: 🚨 Fix, 🎳 현승

#177 🚨 [Fix] 영상 다운로드 권한 부여 API 수정
  scapture/src/main/java/com/server/scapture/video/service/VideoServiceImpl.java
Labels: 🚨 Fix, 🎳 현승

#178 ♻️ [Refactoring] 구독 생성 갱신 API 병합
  scapture/src/main/java/com/server/scapture/user/controller/UserController.java
  scapture/src/main/java/com/server/scapture/user/service/UserService.java
  scapture/src/main/java/com/server/scapture/user/service/UserServiceImpl.java
Labels: 🛠️ Refactoring, 🍀 혜진

#180 ✨ [Feat] 메인 페이지 API 구현
  scapture/src/main/java/com/server/scapture/stadium/controller/StadiumController.java
  scapture/src/main/java/com/server/scapture/stadium/dto/GetMainInfoPopularDto.java
  scapture/src/main/java/com/server/scapture/stadium/dto/GetMainInfoResponseDto.java
  scapture/src/main/java/com/server/scapture/stadium/dto/GetMainInfoStadiumDto.java
  scapture/src/main/java/com/server/scapture/stadium/service/StadiumService.java
  scapture/src/main/java/com/server/scapture/stadium/service/StadiumServiceImpl.java
  scapture/src/main/java/com/server/scapture/video/repository/VideoRepository.java
Labels: 🎳 현승, ✨ Feat

#181 ♻️ [Refactoring] 버내너 잔액조회에 checkRoll 추가
  scapture/src/main/java/com/server/scapture/user/service/UserServiceImpl.java
Labels: :recycle: Refactoring, 🍀 혜진

#182 ♻️ [Refact] 소셜로그인 코드 리펙터링
  scapture/src/main/java/com/server/scapture/oauth/controller/SignController.java
  scapture/src/main/java/com/server/scapture/oauth/service/GoogleLoginServiceImpl.java
  scapture/src/main/java/com/server/scapture/oauth/service/KakaoLoginServiceImpl.java
  scapture/src/main/java/com/server/scapture/oauth/service/NaverLoginServiceImpl.java
Labels: :recycle: Refactoring, 🍀 혜진

#185 ✨ [Feat] 영상 녹화 정보 조회 API 구현
  scapture/src/main/java/com/server/scapture/Ip/repository/IpRepository.java
  scapture/src/main/java/com/server/scapture/domain/Ip.java
  scapture/src/main/java/com/server/scapture/video/controller/VideoController.java
  scapture/src/main/java/com/server/scapture/video/dto/GetRecordInfoResponseDto.java
  scapture/src/main/java/com/server/scapture/video/service/VideoService.java
  scapture/src/main/java/com/server/scapture/video/service/VideoServiceImpl.java
Labels: 🎳 현승, ✨ Feat

#187 ✨ [Feat] IP 생성 API 구현
  scapture/src/main/java/com/server/scapture/Ip/controller/IpController.java
  scapture/src/main/java/com/server/scapture/Ip/dto/CreateIpRequestDto.java
  scapture/src/main/java/com/server/scapture/Ip/service/IpService.java
  scapture/src/main/java/com/server/scapture/Ip/service/IpServiceImpl.java
  scapture/src/main/java/com/server/scapture/video/controller/VideoController.java
Labels: 🎳 현승, ✨ Feat

#189 🚨 [Fix] 운영 시간 생성 API 수정
  scapture/src/main/java/com/server/scapture/schedule/dto/CreateScheduleResponseDto.java
  scapture/src/main/java/com/server/scapture/schedule/service/ScheduleServiceImpl.java
Labels: 🚨 Fix, 🎳 현승
